name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${1e347b09-837f-4e64-b6dc-2506111c6079}}
          heroku_app_name: "bookborrowing" #Must be unique in Heroku
          heroku_email: "syazaifah@gmail.com"
